language: node_js
node_js:
  - "6"
script: ./travis.sh
cache:
  directories:
    - node_modules
branches:
  except:
    - master
sudo: false
env:
  - CXX=g++-4.8
  - COMMIT_AUTHOR_EMAIL=travisci@killrvideo.com
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8