language: node_js
node_js:
  - "6"
script:
  - npm run ci
cache:
  directories:
    - node_modules
branches:
  except:
    - master
sudo: false
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8